import './globals.css'
import { Tomorrow } from 'next/font/google'

const tomorrow = Tomorrow({
  subsets: ['latin'],
  weight: ['100','200', '300','400','500','600' ,'700','800'],
})

export const metadata = {
  title: 'Password Generator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={tomorrow.className}>{children}</body>
    </html>
  )
}
